import { useEffect, useMemo, useState } from 'react';
import { Box, Button, Card, CardContent, Grid, LinearProgress, MenuItem, Stack, TextField, Typography, Chip } from '@mui/material';
import api from '../api';
import DataTable from '../components/DataTable';
import SectionTitle from '../components/SectionTitle';
import SummaryCard from '../components/SummaryCard';

const budgetInitial = { title: '', code: '', allowedBudget: 0, expectedCost: 0, responsibleTeamId: '', responsibleUserId: '' };
const vendorInitial = { name: '', vendorType: '', budgetHeadId: '', responsibleTeamId: '', responsibleUserId: '', quotedAmount: 0, finalAmount: 0, dueAmount: 0 };
const expenseInitial = { title: '', expenseType: 'DIRECT', amount: 0, paymentMode: 'CASH', budgetHeadId: '', vendorId: '', paidByUserId: '', approvedByUserId: '' };

export default function BudgetPage() {
  const [heads, setHeads] = useState([]); const [vendors, setVendors] = useState([]); const [expenses, setExpenses] = useState([]); const [teams, setTeams] = useState([]); const [users, setUsers] = useState([]);
  const [budgetForm, setBudgetForm] = useState(budgetInitial); const [vendorForm, setVendorForm] = useState(vendorInitial); const [expenseForm, setExpenseForm] = useState(expenseInitial);
  const load = async () => { const [h, v, e, t, u] = await Promise.all([api.get('/budget-heads'), api.get('/vendors'), api.get('/expenses'), api.get('/teams'), api.get('/users')]); setHeads(h.data); setVendors(v.data); setExpenses(e.data); setTeams(t.data); setUsers(u.data); };
  useEffect(() => { load(); }, []);
  const totals = useMemo(() => ({ allowed: heads.reduce((a, x) => a + (x.allowedBudget || 0), 0), expected: heads.reduce((a, x) => a + (x.expectedCost || 0), 0), actual: heads.reduce((a, x) => a + (x.actualExpense || 0), 0), due: vendors.reduce((a, x) => a + (x.dueAmount || 0), 0) }), [heads, vendors]);
  const createBudget = async (e) => { e.preventDefault(); await api.post('/budget-heads', budgetForm); setBudgetForm(budgetInitial); load(); };
  const createVendor = async (e) => { e.preventDefault(); await api.post('/vendors', vendorForm); setVendorForm(vendorInitial); load(); };
  const createExpense = async (e) => { e.preventDefault(); await api.post('/expenses', expenseForm); setExpenseForm(expenseInitial); load(); };
  const budgetUtil = totals.allowed ? Math.round((totals.actual / totals.allowed) * 100) : 0;

  return <Box>
    <SectionTitle title="Finance Operations" subtitle="Budget heads, vendors, dues, and expense controls with mobile-friendly cards and desktop tables." />
    <Grid container spacing={2}><Grid item xs={6} md={3}><SummaryCard title="Allowed" value={`₹${totals.allowed}`} /></Grid><Grid item xs={6} md={3}><SummaryCard title="Expected" value={`₹${totals.expected}`} /></Grid><Grid item xs={6} md={3}><SummaryCard title="Actual" value={`₹${totals.actual}`} tone={totals.actual > totals.allowed ? 'warning' : 'default'} /></Grid><Grid item xs={6} md={3}><SummaryCard title="Pending Due" value={`₹${totals.due}`} tone="warning" /></Grid></Grid>
    <Card sx={{ mt: 2 }}><CardContent><Typography variant="subtitle2" gutterBottom>Budget Utilization</Typography><LinearProgress variant="determinate" value={Math.min(100, budgetUtil)} /><Typography variant="caption">{budgetUtil}% utilized</Typography></CardContent></Card>

    <Grid container spacing={2} sx={{ mt: 0.5 }}><Grid item xs={12} md={6}><Card component="form" onSubmit={createBudget}><CardContent><Typography variant="h6">Budget Head</Typography><Grid container spacing={1}>{[['Title','title'],['Code','code']].map(([l,k]) => <Grid item xs={12} sm={6} key={k}><TextField label={l} value={budgetForm[k]} onChange={(e)=>setBudgetForm({...budgetForm,[k]:e.target.value})} /></Grid>)}<Grid item xs={6}><TextField type="number" label="Allowed" value={budgetForm.allowedBudget} onChange={(e)=>setBudgetForm({...budgetForm,allowedBudget:Number(e.target.value)})} /></Grid><Grid item xs={6}><TextField type="number" label="Expected" value={budgetForm.expectedCost} onChange={(e)=>setBudgetForm({...budgetForm,expectedCost:Number(e.target.value)})} /></Grid><Grid item xs={6}><TextField select label="Team" value={budgetForm.responsibleTeamId} onChange={(e)=>setBudgetForm({...budgetForm,responsibleTeamId:e.target.value})}><MenuItem value="">None</MenuItem>{teams.map((x)=><MenuItem key={x._id} value={x._id}>{x.name}</MenuItem>)}</TextField></Grid><Grid item xs={6}><TextField select label="User" value={budgetForm.responsibleUserId} onChange={(e)=>setBudgetForm({...budgetForm,responsibleUserId:e.target.value})}><MenuItem value="">None</MenuItem>{users.map((x)=><MenuItem key={x._id} value={x._id}>{x.name}</MenuItem>)}</TextField></Grid><Grid item xs={12}><Button variant="contained" type="submit">Add Budget Head</Button></Grid></Grid></CardContent></Card></Grid>
      <Grid item xs={12} md={6}><Card component="form" onSubmit={createVendor}><CardContent><Typography variant="h6">Vendor</Typography><Grid container spacing={1}><Grid item xs={12} sm={6}><TextField label="Vendor name" value={vendorForm.name} onChange={(e)=>setVendorForm({...vendorForm,name:e.target.value})} /></Grid><Grid item xs={12} sm={6}><TextField label="Vendor type" value={vendorForm.vendorType} onChange={(e)=>setVendorForm({...vendorForm,vendorType:e.target.value})} /></Grid><Grid item xs={12}><TextField select label="Budget head" value={vendorForm.budgetHeadId} onChange={(e)=>setVendorForm({...vendorForm,budgetHeadId:e.target.value})}><MenuItem value="">None</MenuItem>{heads.map((x)=><MenuItem key={x._id} value={x._id}>{x.title}</MenuItem>)}</TextField></Grid><Grid item xs={4}><TextField type="number" label="Quoted" value={vendorForm.quotedAmount} onChange={(e)=>setVendorForm({...vendorForm,quotedAmount:Number(e.target.value)})} /></Grid><Grid item xs={4}><TextField type="number" label="Final" value={vendorForm.finalAmount} onChange={(e)=>setVendorForm({...vendorForm,finalAmount:Number(e.target.value)})} /></Grid><Grid item xs={4}><TextField type="number" label="Due" value={vendorForm.dueAmount} onChange={(e)=>setVendorForm({...vendorForm,dueAmount:Number(e.target.value)})} /></Grid><Grid item xs={12}><Button variant="contained" type="submit">Add Vendor</Button></Grid></Grid></CardContent></Card></Grid></Grid>

    <Card component="form" onSubmit={createExpense} sx={{ mt: 2 }}><CardContent><Typography variant="h6">Expense Entry</Typography><Grid container spacing={1}><Grid item xs={12} md={3}><TextField label="Title" value={expenseForm.title} onChange={(e)=>setExpenseForm({...expenseForm,title:e.target.value})} /></Grid><Grid item xs={6} md={2}><TextField select label="Type" value={expenseForm.expenseType} onChange={(e)=>setExpenseForm({...expenseForm,expenseType:e.target.value})}>{['VENDOR','DIRECT','EMERGENCY','TEAM_PURCHASE'].map((x)=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid item xs={6} md={2}><TextField type="number" label="Amount" value={expenseForm.amount} onChange={(e)=>setExpenseForm({...expenseForm,amount:Number(e.target.value)})} /></Grid><Grid item xs={6} md={2}><TextField select label="Mode" value={expenseForm.paymentMode} onChange={(e)=>setExpenseForm({...expenseForm,paymentMode:e.target.value})}>{['CASH','UPI','BANK','CHEQUE','OTHER'].map((x)=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid item xs={6} md={3}><TextField select label="Vendor" value={expenseForm.vendorId} onChange={(e)=>setExpenseForm({...expenseForm,vendorId:e.target.value})}><MenuItem value="">None</MenuItem>{vendors.map((x)=><MenuItem key={x._id} value={x._id}>{x.name}</MenuItem>)}</TextField></Grid><Grid item xs={12}><Button variant="contained" type="submit">Record Expense</Button></Grid></Grid></CardContent></Card>

    <Grid container spacing={2} sx={{ mt: 0.5 }}><Grid item xs={12} md={6}><DataTable headers={['Head','Allowed','Expected','Actual','Owner']} rows={heads.map((x)=>[x.title,x.allowedBudget,x.expectedCost,<Chip size="small" color={(x.actualExpense||0)>(x.allowedBudget||0)?'warning':'default'} label={x.actualExpense||0} />,x.responsibleUserId?.name||x.responsibleTeamId?.name||'-'])} /></Grid><Grid item xs={12} md={6}><DataTable headers={['Vendor','Type','Quoted','Due','Status']} rows={vendors.map((x)=>[x.name,x.vendorType,x.quotedAmount||0,<Chip size="small" color={(x.dueAmount||0)>0?'warning':'success'} label={x.dueAmount||0} />,x.paymentStatus||'-'])} /></Grid></Grid>
  </Box>;
}
